name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # or 'source', depending on your setup

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # Specify Ruby 3.1 or higher

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: ./deploy.sh  # Run your deploy.sh script